{
  "name": "RevenueOS_Sample",
  "compatibilityLevel": 1550,
  "model": {
    "culture": "en-US",
    "tables": [
      {
        "name": "orders",
        "columns": [
          {
            "name": "order_id",
            "dataType": "string",
            "sourceColumn": "order_id",
            "summarizeBy": "none"
          },
          {
            "name": "customer_id",
            "dataType": "string",
            "sourceColumn": "customer_id",
            "summarizeBy": "none"
          },
          {
            "name": "product_id",
            "dataType": "string",
            "sourceColumn": "product_id",
            "summarizeBy": "none"
          },
          {
            "name": "order_date",
            "dataType": "dateTime",
            "sourceColumn": "order_date",
            "summarizeBy": "none"
          },
          {
            "name": "quantity",
            "dataType": "int64",
            "sourceColumn": "quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "unit_price",
            "dataType": "double",
            "sourceColumn": "unit_price",
            "summarizeBy": "sum"
          },
          {
            "name": "discount",
            "dataType": "double",
            "sourceColumn": "discount",
            "summarizeBy": "sum"
          },
          {
            "name": "channel",
            "dataType": "string",
            "sourceColumn": "channel",
            "summarizeBy": "none"
          },
          {
            "name": "location",
            "dataType": "string",
            "sourceColumn": "location",
            "summarizeBy": "none"
          },
          {
            "name": "status",
            "dataType": "string",
            "sourceColumn": "status",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "orders-Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let Source = Csv.Document(File.Contents(\"C:/Partition/SERIOUS PROJECTS/RevenueOS/data/raw/excel/powerbi_export_revenueos_sample_20261004_113020/csv/orders.csv\"),[Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.None]), #\"Promoted\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]) in #\"Promoted\""
              ]
            }
          }
        ]
      },
      {
        "name": "customers",
        "columns": [
          {
            "name": "customer_id",
            "dataType": "string",
            "sourceColumn": "customer_id",
            "summarizeBy": "none"
          },
          {
            "name": "name",
            "dataType": "string",
            "sourceColumn": "name",
            "summarizeBy": "none"
          },
          {
            "name": "email",
            "dataType": "string",
            "sourceColumn": "email",
            "summarizeBy": "none"
          },
          {
            "name": "city",
            "dataType": "string",
            "sourceColumn": "city",
            "summarizeBy": "none"
          },
          {
            "name": "region",
            "dataType": "string",
            "sourceColumn": "region",
            "summarizeBy": "none"
          },
          {
            "name": "signup_date",
            "dataType": "dateTime",
            "sourceColumn": "signup_date",
            "summarizeBy": "none"
          },
          {
            "name": "segment",
            "dataType": "string",
            "sourceColumn": "segment",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "customers-Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let Source = Csv.Document(File.Contents(\"C:/Partition/SERIOUS PROJECTS/RevenueOS/data/raw/excel/powerbi_export_revenueos_sample_20261004_113020/csv/customers.csv\"),[Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.None]), #\"Promoted\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]) in #\"Promoted\""
              ]
            }
          }
        ]
      },
      {
        "name": "products",
        "columns": [
          {
            "name": "product_id",
            "dataType": "string",
            "sourceColumn": "product_id",
            "summarizeBy": "none"
          },
          {
            "name": "product_name",
            "dataType": "string",
            "sourceColumn": "product_name",
            "summarizeBy": "none"
          },
          {
            "name": "category",
            "dataType": "string",
            "sourceColumn": "category",
            "summarizeBy": "none"
          },
          {
            "name": "subcategory",
            "dataType": "string",
            "sourceColumn": "subcategory",
            "summarizeBy": "none"
          },
          {
            "name": "supplier",
            "dataType": "string",
            "sourceColumn": "supplier",
            "summarizeBy": "none"
          },
          {
            "name": "cost",
            "dataType": "int64",
            "sourceColumn": "cost",
            "summarizeBy": "sum"
          },
          {
            "name": "selling_price",
            "dataType": "int64",
            "sourceColumn": "selling_price",
            "summarizeBy": "sum"
          }
        ],
        "partitions": [
          {
            "name": "products-Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let Source = Csv.Document(File.Contents(\"C:/Partition/SERIOUS PROJECTS/RevenueOS/data/raw/excel/powerbi_export_revenueos_sample_20261004_113020/csv/products.csv\"),[Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.None]), #\"Promoted\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]) in #\"Promoted\""
              ]
            }
          }
        ]
      },
      {
        "name": "payments",
        "columns": [
          {
            "name": "payment_id",
            "dataType": "string",
            "sourceColumn": "payment_id",
            "summarizeBy": "none"
          },
          {
            "name": "order_id",
            "dataType": "string",
            "sourceColumn": "order_id",
            "summarizeBy": "none"
          },
          {
            "name": "payment_date",
            "dataType": "dateTime",
            "sourceColumn": "payment_date",
            "summarizeBy": "none"
          },
          {
            "name": "payment_method",
            "dataType": "string",
            "sourceColumn": "payment_method",
            "summarizeBy": "none"
          },
          {
            "name": "amount",
            "dataType": "double",
            "sourceColumn": "amount",
            "summarizeBy": "sum"
          },
          {
            "name": "payment_status",
            "dataType": "string",
            "sourceColumn": "payment_status",
            "summarizeBy": "none"
          },
          {
            "name": "failure_reason",
            "dataType": "string",
            "sourceColumn": "failure_reason",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "payments-Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let Source = Csv.Document(File.Contents(\"C:/Partition/SERIOUS PROJECTS/RevenueOS/data/raw/excel/powerbi_export_revenueos_sample_20261004_113020/csv/payments.csv\"),[Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.None]), #\"Promoted\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]) in #\"Promoted\""
              ]
            }
          }
        ]
      },
      {
        "name": "returns",
        "columns": [
          {
            "name": "return_id",
            "dataType": "string",
            "sourceColumn": "return_id",
            "summarizeBy": "none"
          },
          {
            "name": "order_id",
            "dataType": "string",
            "sourceColumn": "order_id",
            "summarizeBy": "none"
          },
          {
            "name": "product_id",
            "dataType": "string",
            "sourceColumn": "product_id",
            "summarizeBy": "none"
          },
          {
            "name": "return_date",
            "dataType": "dateTime",
            "sourceColumn": "return_date",
            "summarizeBy": "none"
          },
          {
            "name": "quantity_returned",
            "dataType": "int64",
            "sourceColumn": "quantity_returned",
            "summarizeBy": "sum"
          },
          {
            "name": "return_reason",
            "dataType": "string",
            "sourceColumn": "return_reason",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "returns-Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let Source = Csv.Document(File.Contents(\"C:/Partition/SERIOUS PROJECTS/RevenueOS/data/raw/excel/powerbi_export_revenueos_sample_20261004_113020/csv/returns.csv\"),[Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.None]), #\"Promoted\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]) in #\"Promoted\""
              ]
            }
          }
        ]
      },
      {
        "name": "inventory",
        "columns": [
          {
            "name": "product_id",
            "dataType": "string",
            "sourceColumn": "product_id",
            "summarizeBy": "none"
          },
          {
            "name": "warehouse",
            "dataType": "string",
            "sourceColumn": "warehouse",
            "summarizeBy": "none"
          },
          {
            "name": "snapshot_date",
            "dataType": "dateTime",
            "sourceColumn": "snapshot_date",
            "summarizeBy": "none"
          },
          {
            "name": "units_available",
            "dataType": "int64",
            "sourceColumn": "units_available",
            "summarizeBy": "sum"
          },
          {
            "name": "units_reserved",
            "dataType": "int64",
            "sourceColumn": "units_reserved",
            "summarizeBy": "sum"
          },
          {
            "name": "units_sold",
            "dataType": "int64",
            "sourceColumn": "units_sold",
            "summarizeBy": "sum"
          }
        ],
        "partitions": [
          {
            "name": "inventory-Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let Source = Csv.Document(File.Contents(\"C:/Partition/SERIOUS PROJECTS/RevenueOS/data/raw/excel/powerbi_export_revenueos_sample_20261004_113020/csv/inventory.csv\"),[Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.None]), #\"Promoted\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]) in #\"Promoted\""
              ]
            }
          }
        ]
      },
      {
        "name": "marketing",
        "columns": [
          {
            "name": "campaign_id",
            "dataType": "string",
            "sourceColumn": "campaign_id",
            "summarizeBy": "none"
          },
          {
            "name": "channel",
            "dataType": "string",
            "sourceColumn": "channel",
            "summarizeBy": "none"
          },
          {
            "name": "date",
            "dataType": "dateTime",
            "sourceColumn": "date",
            "summarizeBy": "none"
          },
          {
            "name": "spend",
            "dataType": "double",
            "sourceColumn": "spend",
            "summarizeBy": "sum"
          },
          {
            "name": "impressions",
            "dataType": "int64",
            "sourceColumn": "impressions",
            "summarizeBy": "sum"
          },
          {
            "name": "clicks",
            "dataType": "int64",
            "sourceColumn": "clicks",
            "summarizeBy": "sum"
          },
          {
            "name": "orders_attributed",
            "dataType": "int64",
            "sourceColumn": "orders_attributed",
            "summarizeBy": "sum"
          },
          {
            "name": "revenue_attributed",
            "dataType": "double",
            "sourceColumn": "revenue_attributed",
            "summarizeBy": "sum"
          }
        ],
        "partitions": [
          {
            "name": "marketing-Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let Source = Csv.Document(File.Contents(\"C:/Partition/SERIOUS PROJECTS/RevenueOS/data/raw/excel/powerbi_export_revenueos_sample_20261004_113020/csv/marketing.csv\"),[Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.None]), #\"Promoted\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]) in #\"Promoted\""
              ]
            }
          }
        ]
      },
      {
        "name": "dim_date",
        "columns": [
          {
            "name": "date",
            "dataType": "dateTime",
            "sourceColumn": "date",
            "summarizeBy": "none"
          },
          {
            "name": "full_date",
            "dataType": "dateTime",
            "sourceColumn": "full_date",
            "summarizeBy": "none"
          },
          {
            "name": "year",
            "dataType": "int64",
            "sourceColumn": "year",
            "summarizeBy": "none"
          },
          {
            "name": "quarter",
            "dataType": "string",
            "sourceColumn": "quarter",
            "summarizeBy": "none"
          },
          {
            "name": "quarter_number",
            "dataType": "int64",
            "sourceColumn": "quarter_number",
            "summarizeBy": "none"
          },
          {
            "name": "month",
            "dataType": "int64",
            "sourceColumn": "month",
            "summarizeBy": "sum"
          },
          {
            "name": "month_name",
            "dataType": "string",
            "sourceColumn": "month_name",
            "summarizeBy": "none"
          },
          {
            "name": "month_year",
            "dataType": "string",
            "sourceColumn": "month_year",
            "summarizeBy": "none"
          },
          {
            "name": "month_year_sort",
            "dataType": "int64",
            "sourceColumn": "month_year_sort",
            "summarizeBy": "none"
          },
          {
            "name": "day_of_month",
            "dataType": "dateTime",
            "sourceColumn": "day_of_month",
            "summarizeBy": "none"
          },
          {
            "name": "day_of_week",
            "dataType": "dateTime",
            "sourceColumn": "day_of_week",
            "summarizeBy": "none"
          },
          {
            "name": "day_name",
            "dataType": "string",
            "sourceColumn": "day_name",
            "summarizeBy": "none"
          },
          {
            "name": "week_number",
            "dataType": "double",
            "sourceColumn": "week_number",
            "summarizeBy": "sum"
          },
          {
            "name": "is_weekend",
            "dataType": "int64",
            "sourceColumn": "is_weekend",
            "summarizeBy": "sum"
          }
        ],
        "partitions": [
          {
            "name": "dim_date-Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let Source = Csv.Document(File.Contents(\"C:/Partition/SERIOUS PROJECTS/RevenueOS/data/raw/excel/powerbi_export_revenueos_sample_20261004_113020/csv/dim_date.csv\"),[Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.None]), #\"Promoted\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]) in #\"Promoted\""
              ]
            }
          }
        ]
      },
      {
        "name": "_Measures",
        "columns": [
          {
            "name": "Measure_Placeholder",
            "dataType": "string",
            "sourceColumn": "Measure_Placeholder",
            "isHidden": true
          }
        ],
        "measures": [
          {
            "name": "Payments Count",
            "expression": "DISTINCTCOUNT(payments[payment_id])",
            "formatString": "#,0",
            "description": "Distinct count of payment_id in payments",
            "displayFolder": "01 Volume & Counts"
          },
          {
            "name": "Total Amount",
            "expression": "SUM(payments[amount])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "description": "Aggregated sum of amount in payments",
            "displayFolder": "02 Core Metrics"
          },
          {
            "name": "Average Amount",
            "expression": "AVERAGE(payments[amount])",
            "formatString": "\\$#,##0.00",
            "description": "Arithmetic average of amount in payments",
            "displayFolder": "02 Core Metrics"
          },
          {
            "name": "Amount YTD",
            "expression": "TOTALYTD([Total Amount], dim_date[date])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "description": "Year-to-date calculation for Total Amount",
            "displayFolder": "04 Time Intelligence"
          },
          {
            "name": "Amount Prior Month",
            "expression": "CALCULATE([Total Amount], PREVIOUSMONTH(dim_date[date]))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "description": "Previous month value for Total Amount",
            "displayFolder": "04 Time Intelligence"
          },
          {
            "name": "Amount MoM %",
            "expression": "DIVIDE([Total Amount] - [Amount Prior Month], [Amount Prior Month], 0)",
            "formatString": "0.0%",
            "description": "Month-over-month growth percentage for Total Amount",
            "displayFolder": "04 Time Intelligence"
          },
          {
            "name": "Amount Prior Year",
            "expression": "CALCULATE([Total Amount], SAMEPERIODLASTYEAR(dim_date[date]))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "description": "Same period last year for Total Amount",
            "displayFolder": "04 Time Intelligence"
          },
          {
            "name": "Amount YoY %",
            "expression": "DIVIDE([Total Amount] - [Amount Prior Year], [Amount Prior Year], 0)",
            "formatString": "0.0%",
            "description": "Year-over-year growth percentage for Total Amount",
            "displayFolder": "04 Time Intelligence"
          },
          {
            "name": "Returns Count",
            "expression": "DISTINCTCOUNT(returns[return_id])",
            "formatString": "#,0",
            "description": "Distinct count of return_id in returns",
            "displayFolder": "01 Volume & Counts"
          },
          {
            "name": "Total Quantity Returned",
            "expression": "SUM(returns[quantity_returned])",
            "formatString": "#,0",
            "description": "Aggregated sum of quantity_returned in returns",
            "displayFolder": "02 Core Metrics"
          },
          {
            "name": "Average Quantity Returned",
            "expression": "AVERAGE(returns[quantity_returned])",
            "formatString": "#,##0.00",
            "description": "Arithmetic average of quantity_returned in returns",
            "displayFolder": "02 Core Metrics"
          },
          {
            "name": "Quantity Returned YTD",
            "expression": "TOTALYTD([Total Quantity Returned], dim_date[date])",
            "formatString": "#,0",
            "description": "Year-to-date calculation for Total Quantity Returned",
            "displayFolder": "04 Time Intelligence"
          },
          {
            "name": "Quantity Returned Prior Month",
            "expression": "CALCULATE([Total Quantity Returned], PREVIOUSMONTH(dim_date[date]))",
            "formatString": "#,0",
            "description": "Previous month value for Total Quantity Returned",
            "displayFolder": "04 Time Intelligence"
          },
          {
            "name": "Quantity Returned MoM %",
            "expression": "DIVIDE([Total Quantity Returned] - [Quantity Returned Prior Month], [Quantity Returned Prior Month], 0)",
            "formatString": "0.0%",
            "description": "Month-over-month growth percentage for Total Quantity Returned",
            "displayFolder": "04 Time Intelligence"
          },
          {
            "name": "Quantity Returned Prior Year",
            "expression": "CALCULATE([Total Quantity Returned], SAMEPERIODLASTYEAR(dim_date[date]))",
            "formatString": "#,0",
            "description": "Same period last year for Total Quantity Returned",
            "displayFolder": "04 Time Intelligence"
          },
          {
            "name": "Quantity Returned YoY %",
            "expression": "DIVIDE([Total Quantity Returned] - [Quantity Returned Prior Year], [Quantity Returned Prior Year], 0)",
            "formatString": "0.0%",
            "description": "Year-over-year growth percentage for Total Quantity Returned",
            "displayFolder": "04 Time Intelligence"
          },
          {
            "name": "Total Inventory Rows",
            "expression": "COUNTROWS(inventory)",
            "formatString": "#,0",
            "description": "Total rows in inventory",
            "displayFolder": "01 Volume & Counts"
          },
          {
            "name": "Total Units Available",
            "expression": "SUM(inventory[units_available])",
            "formatString": "#,0",
            "description": "Aggregated sum of units_available in inventory",
            "displayFolder": "02 Core Metrics"
          },
          {
            "name": "Average Units Available",
            "expression": "AVERAGE(inventory[units_available])",
            "formatString": "#,##0.00",
            "description": "Arithmetic average of units_available in inventory",
            "displayFolder": "02 Core Metrics"
          },
          {
            "name": "Units Available YTD",
            "expression": "TOTALYTD([Total Units Available], dim_date[date])",
            "formatString": "#,0",
            "description": "Year-to-date calculation for Total Units Available",
            "displayFolder": "04 Time Intelligence"
          },
          {
            "name": "Units Available Prior Month",
            "expression": "CALCULATE([Total Units Available], PREVIOUSMONTH(dim_date[date]))",
            "formatString": "#,0",
            "description": "Previous month value for Total Units Available",
            "displayFolder": "04 Time Intelligence"
          },
          {
            "name": "Units Available MoM %",
            "expression": "DIVIDE([Total Units Available] - [Units Available Prior Month], [Units Available Prior Month], 0)",
            "formatString": "0.0%",
            "description": "Month-over-month growth percentage for Total Units Available",
            "displayFolder": "04 Time Intelligence"
          },
          {
            "name": "Units Available Prior Year",
            "expression": "CALCULATE([Total Units Available], SAMEPERIODLASTYEAR(dim_date[date]))",
            "formatString": "#,0",
            "description": "Same period last year for Total Units Available",
            "displayFolder": "04 Time Intelligence"
          },
          {
            "name": "Units Available YoY %",
            "expression": "DIVIDE([Total Units Available] - [Units Available Prior Year], [Units Available Prior Year], 0)",
            "formatString": "0.0%",
            "description": "Year-over-year growth percentage for Total Units Available",
            "displayFolder": "04 Time Intelligence"
          },
          {
            "name": "Total Units Reserved",
            "expression": "SUM(inventory[units_reserved])",
            "formatString": "#,0",
            "description": "Aggregated sum of units_reserved in inventory",
            "displayFolder": "02 Core Metrics"
          },
          {
            "name": "Average Units Reserved",
            "expression": "AVERAGE(inventory[units_reserved])",
            "formatString": "#,##0.00",
            "description": "Arithmetic average of units_reserved in inventory",
            "displayFolder": "02 Core Metrics"
          },
          {
            "name": "Units Reserved YTD",
            "expression": "TOTALYTD([Total Units Reserved], dim_date[date])",
            "formatString": "#,0",
            "description": "Year-to-date calculation for Total Units Reserved",
            "displayFolder": "04 Time Intelligence"
          },
          {
            "name": "Units Reserved Prior Month",
            "expression": "CALCULATE([Total Units Reserved], PREVIOUSMONTH(dim_date[date]))",
            "formatString": "#,0",
            "description": "Previous month value for Total Units Reserved",
            "displayFolder": "04 Time Intelligence"
          },
          {
            "name": "Units Reserved MoM %",
            "expression": "DIVIDE([Total Units Reserved] - [Units Reserved Prior Month], [Units Reserved Prior Month], 0)",
            "formatString": "0.0%",
            "description": "Month-over-month growth percentage for Total Units Reserved",
            "displayFolder": "04 Time Intelligence"
          },
          {
            "name": "Units Reserved Prior Year",
            "expression": "CALCULATE([Total Units Reserved], SAMEPERIODLASTYEAR(dim_date[date]))",
            "formatString": "#,0",
            "description": "Same period last year for Total Units Reserved",
            "displayFolder": "04 Time Intelligence"
          },
          {
            "name": "Units Reserved YoY %",
            "expression": "DIVIDE([Total Units Reserved] - [Units Reserved Prior Year], [Units Reserved Prior Year], 0)",
            "formatString": "0.0%",
            "description": "Year-over-year growth percentage for Total Units Reserved",
            "displayFolder": "04 Time Intelligence"
          },
          {
            "name": "Total Units Sold",
            "expression": "SUM(inventory[units_sold])",
            "formatString": "#,0",
            "description": "Aggregated sum of units_sold in inventory",
            "displayFolder": "02 Core Metrics"
          },
          {
            "name": "Average Units Sold",
            "expression": "AVERAGE(inventory[units_sold])",
            "formatString": "#,##0.00",
            "description": "Arithmetic average of units_sold in inventory",
            "displayFolder": "02 Core Metrics"
          },
          {
            "name": "Units Sold YTD",
            "expression": "TOTALYTD([Total Units Sold], dim_date[date])",
            "formatString": "#,0",
            "description": "Year-to-date calculation for Total Units Sold",
            "displayFolder": "04 Time Intelligence"
          },
          {
            "name": "Units Sold Prior Month",
            "expression": "CALCULATE([Total Units Sold], PREVIOUSMONTH(dim_date[date]))",
            "formatString": "#,0",
            "description": "Previous month value for Total Units Sold",
            "displayFolder": "04 Time Intelligence"
          },
          {
            "name": "Units Sold MoM %",
            "expression": "DIVIDE([Total Units Sold] - [Units Sold Prior Month], [Units Sold Prior Month], 0)",
            "formatString": "0.0%",
            "description": "Month-over-month growth percentage for Total Units Sold",
            "displayFolder": "04 Time Intelligence"
          },
          {
            "name": "Units Sold Prior Year",
            "expression": "CALCULATE([Total Units Sold], SAMEPERIODLASTYEAR(dim_date[date]))",
            "formatString": "#,0",
            "description": "Same period last year for Total Units Sold",
            "displayFolder": "04 Time Intelligence"
          },
          {
            "name": "Units Sold YoY %",
            "expression": "DIVIDE([Total Units Sold] - [Units Sold Prior Year], [Units Sold Prior Year], 0)",
            "formatString": "0.0%",
            "description": "Year-over-year growth percentage for Total Units Sold",
            "displayFolder": "04 Time Intelligence"
          },
          {
            "name": "Total Marketing Rows",
            "expression": "COUNTROWS(marketing)",
            "formatString": "#,0",
            "description": "Total rows in marketing",
            "displayFolder": "01 Volume & Counts"
          },
          {
            "name": "Total Spend",
            "expression": "SUM(marketing[spend])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "description": "Aggregated sum of spend in marketing",
            "displayFolder": "02 Core Metrics"
          },
          {
            "name": "Average Spend",
            "expression": "AVERAGE(marketing[spend])",
            "formatString": "\\$#,##0.00",
            "description": "Arithmetic average of spend in marketing",
            "displayFolder": "02 Core Metrics"
          },
          {
            "name": "Spend YTD",
            "expression": "TOTALYTD([Total Spend], dim_date[date])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "description": "Year-to-date calculation for Total Spend",
            "displayFolder": "04 Time Intelligence"
          },
          {
            "name": "Spend Prior Month",
            "expression": "CALCULATE([Total Spend], PREVIOUSMONTH(dim_date[date]))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "description": "Previous month value for Total Spend",
            "displayFolder": "04 Time Intelligence"
          },
          {
            "name": "Spend MoM %",
            "expression": "DIVIDE([Total Spend] - [Spend Prior Month], [Spend Prior Month], 0)",
            "formatString": "0.0%",
            "description": "Month-over-month growth percentage for Total Spend",
            "displayFolder": "04 Time Intelligence"
          },
          {
            "name": "Spend Prior Year",
            "expression": "CALCULATE([Total Spend], SAMEPERIODLASTYEAR(dim_date[date]))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "description": "Same period last year for Total Spend",
            "displayFolder": "04 Time Intelligence"
          },
          {
            "name": "Spend YoY %",
            "expression": "DIVIDE([Total Spend] - [Spend Prior Year], [Spend Prior Year], 0)",
            "formatString": "0.0%",
            "description": "Year-over-year growth percentage for Total Spend",
            "displayFolder": "04 Time Intelligence"
          },
          {
            "name": "Total Impressions",
            "expression": "SUM(marketing[impressions])",
            "formatString": "#,0",
            "description": "Aggregated sum of impressions in marketing",
            "displayFolder": "02 Core Metrics"
          },
          {
            "name": "Average Impressions",
            "expression": "AVERAGE(marketing[impressions])",
            "formatString": "#,##0.00",
            "description": "Arithmetic average of impressions in marketing",
            "displayFolder": "02 Core Metrics"
          },
          {
            "name": "Impressions YTD",
            "expression": "TOTALYTD([Total Impressions], dim_date[date])",
            "formatString": "#,0",
            "description": "Year-to-date calculation for Total Impressions",
            "displayFolder": "04 Time Intelligence"
          },
          {
            "name": "Impressions Prior Month",
            "expression": "CALCULATE([Total Impressions], PREVIOUSMONTH(dim_date[date]))",
            "formatString": "#,0",
            "description": "Previous month value for Total Impressions",
            "displayFolder": "04 Time Intelligence"
          },
          {
            "name": "Impressions MoM %",
            "expression": "DIVIDE([Total Impressions] - [Impressions Prior Month], [Impressions Prior Month], 0)",
            "formatString": "0.0%",
            "description": "Month-over-month growth percentage for Total Impressions",
            "displayFolder": "04 Time Intelligence"
          },
          {
            "name": "Impressions Prior Year",
            "expression": "CALCULATE([Total Impressions], SAMEPERIODLASTYEAR(dim_date[date]))",
            "formatString": "#,0",
            "description": "Same period last year for Total Impressions",
            "displayFolder": "04 Time Intelligence"
          },
          {
            "name": "Impressions YoY %",
            "expression": "DIVIDE([Total Impressions] - [Impressions Prior Year], [Impressions Prior Year], 0)",
            "formatString": "0.0%",
            "description": "Year-over-year growth percentage for Total Impressions",
            "displayFolder": "04 Time Intelligence"
          },
          {
            "name": "Total Clicks",
            "expression": "SUM(marketing[clicks])",
            "formatString": "#,0",
            "description": "Aggregated sum of clicks in marketing",
            "displayFolder": "02 Core Metrics"
          },
          {
            "name": "Average Clicks",
            "expression": "AVERAGE(marketing[clicks])",
            "formatString": "#,##0.00",
            "description": "Arithmetic average of clicks in marketing",
            "displayFolder": "02 Core Metrics"
          },
          {
            "name": "Clicks YTD",
            "expression": "TOTALYTD([Total Clicks], dim_date[date])",
            "formatString": "#,0",
            "description": "Year-to-date calculation for Total Clicks",
            "displayFolder": "04 Time Intelligence"
          },
          {
            "name": "Clicks Prior Month",
            "expression": "CALCULATE([Total Clicks], PREVIOUSMONTH(dim_date[date]))",
            "formatString": "#,0",
            "description": "Previous month value for Total Clicks",
            "displayFolder": "04 Time Intelligence"
          },
          {
            "name": "Clicks MoM %",
            "expression": "DIVIDE([Total Clicks] - [Clicks Prior Month], [Clicks Prior Month], 0)",
            "formatString": "0.0%",
            "description": "Month-over-month growth percentage for Total Clicks",
            "displayFolder": "04 Time Intelligence"
          },
          {
            "name": "Clicks Prior Year",
            "expression": "CALCULATE([Total Clicks], SAMEPERIODLASTYEAR(dim_date[date]))",
            "formatString": "#,0",
            "description": "Same period last year for Total Clicks",
            "displayFolder": "04 Time Intelligence"
          },
          {
            "name": "Clicks YoY %",
            "expression": "DIVIDE([Total Clicks] - [Clicks Prior Year], [Clicks Prior Year], 0)",
            "formatString": "0.0%",
            "description": "Year-over-year growth percentage for Total Clicks",
            "displayFolder": "04 Time Intelligence"
          },
          {
            "name": "Total Orders Attributed",
            "expression": "SUM(marketing[orders_attributed])",
            "formatString": "#,0",
            "description": "Aggregated sum of orders_attributed in marketing",
            "displayFolder": "02 Core Metrics"
          },
          {
            "name": "Average Orders Attributed",
            "expression": "AVERAGE(marketing[orders_attributed])",
            "formatString": "#,##0.00",
            "description": "Arithmetic average of orders_attributed in marketing",
            "displayFolder": "02 Core Metrics"
          },
          {
            "name": "Orders Attributed YTD",
            "expression": "TOTALYTD([Total Orders Attributed], dim_date[date])",
            "formatString": "#,0",
            "description": "Year-to-date calculation for Total Orders Attributed",
            "displayFolder": "04 Time Intelligence"
          },
          {
            "name": "Orders Attributed Prior Month",
            "expression": "CALCULATE([Total Orders Attributed], PREVIOUSMONTH(dim_date[date]))",
            "formatString": "#,0",
            "description": "Previous month value for Total Orders Attributed",
            "displayFolder": "04 Time Intelligence"
          },
          {
            "name": "Orders Attributed MoM %",
            "expression": "DIVIDE([Total Orders Attributed] - [Orders Attributed Prior Month], [Orders Attributed Prior Month], 0)",
            "formatString": "0.0%",
            "description": "Month-over-month growth percentage for Total Orders Attributed",
            "displayFolder": "04 Time Intelligence"
          },
          {
            "name": "Orders Attributed Prior Year",
            "expression": "CALCULATE([Total Orders Attributed], SAMEPERIODLASTYEAR(dim_date[date]))",
            "formatString": "#,0",
            "description": "Same period last year for Total Orders Attributed",
            "displayFolder": "04 Time Intelligence"
          },
          {
            "name": "Orders Attributed YoY %",
            "expression": "DIVIDE([Total Orders Attributed] - [Orders Attributed Prior Year], [Orders Attributed Prior Year], 0)",
            "formatString": "0.0%",
            "description": "Year-over-year growth percentage for Total Orders Attributed",
            "displayFolder": "04 Time Intelligence"
          },
          {
            "name": "Total Revenue Attributed",
            "expression": "SUM(marketing[revenue_attributed])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "description": "Aggregated sum of revenue_attributed in marketing",
            "displayFolder": "02 Core Metrics"
          },
          {
            "name": "Average Revenue Attributed",
            "expression": "AVERAGE(marketing[revenue_attributed])",
            "formatString": "\\$#,##0.00",
            "description": "Arithmetic average of revenue_attributed in marketing",
            "displayFolder": "02 Core Metrics"
          },
          {
            "name": "Revenue Attributed YTD",
            "expression": "TOTALYTD([Total Revenue Attributed], dim_date[date])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "description": "Year-to-date calculation for Total Revenue Attributed",
            "displayFolder": "04 Time Intelligence"
          },
          {
            "name": "Revenue Attributed Prior Month",
            "expression": "CALCULATE([Total Revenue Attributed], PREVIOUSMONTH(dim_date[date]))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "description": "Previous month value for Total Revenue Attributed",
            "displayFolder": "04 Time Intelligence"
          },
          {
            "name": "Revenue Attributed MoM %",
            "expression": "DIVIDE([Total Revenue Attributed] - [Revenue Attributed Prior Month], [Revenue Attributed Prior Month], 0)",
            "formatString": "0.0%",
            "description": "Month-over-month growth percentage for Total Revenue Attributed",
            "displayFolder": "04 Time Intelligence"
          },
          {
            "name": "Revenue Attributed Prior Year",
            "expression": "CALCULATE([Total Revenue Attributed], SAMEPERIODLASTYEAR(dim_date[date]))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "description": "Same period last year for Total Revenue Attributed",
            "displayFolder": "04 Time Intelligence"
          },
          {
            "name": "Revenue Attributed YoY %",
            "expression": "DIVIDE([Total Revenue Attributed] - [Revenue Attributed Prior Year], [Revenue Attributed Prior Year], 0)",
            "formatString": "0.0%",
            "description": "Year-over-year growth percentage for Total Revenue Attributed",
            "displayFolder": "04 Time Intelligence"
          },
          {
            "name": "Total Orderss",
            "expression": "DISTINCTCOUNT(orders[order_id])",
            "formatString": "#,0",
            "description": "Total unique count of orders",
            "displayFolder": "05 Entity Intelligence"
          },
          {
            "name": "Total Customerss",
            "expression": "DISTINCTCOUNT(customers[customer_id])",
            "formatString": "#,0",
            "description": "Total unique count of customers",
            "displayFolder": "05 Entity Intelligence"
          },
          {
            "name": "Total Productss",
            "expression": "DISTINCTCOUNT(products[product_id])",
            "formatString": "#,0",
            "description": "Total unique count of products",
            "displayFolder": "05 Entity Intelligence"
          }
        ],
        "partitions": [
          {
            "name": "_Measures-Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let Source = #table({\"Measure_Placeholder\"}, {{\"\"}}) in Source"
              ]
            }
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "payments_order_id_to_orders_order_id",
        "fromTable": "payments",
        "fromColumn": "order_id",
        "toTable": "orders",
        "toColumn": "order_id",
        "crossFilteringBehavior": "oneDirection",
        "securityFilteringBehavior": "oneDirection"
      },
      {
        "name": "returns_order_id_to_orders_order_id",
        "fromTable": "returns",
        "fromColumn": "order_id",
        "toTable": "orders",
        "toColumn": "order_id",
        "crossFilteringBehavior": "oneDirection",
        "securityFilteringBehavior": "oneDirection"
      },
      {
        "name": "orders_customer_id_to_customers_customer_id",
        "fromTable": "orders",
        "fromColumn": "customer_id",
        "toTable": "customers",
        "toColumn": "customer_id",
        "crossFilteringBehavior": "oneDirection",
        "securityFilteringBehavior": "oneDirection"
      },
      {
        "name": "orders_product_id_to_products_product_id",
        "fromTable": "orders",
        "fromColumn": "product_id",
        "toTable": "products",
        "toColumn": "product_id",
        "crossFilteringBehavior": "oneDirection",
        "securityFilteringBehavior": "oneDirection"
      },
      {
        "name": "returns_product_id_to_products_product_id",
        "fromTable": "returns",
        "fromColumn": "product_id",
        "toTable": "products",
        "toColumn": "product_id",
        "crossFilteringBehavior": "oneDirection",
        "securityFilteringBehavior": "oneDirection"
      },
      {
        "name": "inventory_product_id_to_products_product_id",
        "fromTable": "inventory",
        "fromColumn": "product_id",
        "toTable": "products",
        "toColumn": "product_id",
        "crossFilteringBehavior": "oneDirection",
        "securityFilteringBehavior": "oneDirection"
      },
      {
        "name": "orders_order_date_to_dim_date_date",
        "fromTable": "orders",
        "fromColumn": "order_date",
        "toTable": "dim_date",
        "toColumn": "date",
        "crossFilteringBehavior": "oneDirection",
        "securityFilteringBehavior": "oneDirection"
      },
      {
        "name": "customers_signup_date_to_dim_date_date",
        "fromTable": "customers",
        "fromColumn": "signup_date",
        "toTable": "dim_date",
        "toColumn": "date",
        "crossFilteringBehavior": "oneDirection",
        "securityFilteringBehavior": "oneDirection"
      },
      {
        "name": "payments_payment_date_to_dim_date_date",
        "fromTable": "payments",
        "fromColumn": "payment_date",
        "toTable": "dim_date",
        "toColumn": "date",
        "crossFilteringBehavior": "oneDirection",
        "securityFilteringBehavior": "oneDirection"
      },
      {
        "name": "returns_return_date_to_dim_date_date",
        "fromTable": "returns",
        "fromColumn": "return_date",
        "toTable": "dim_date",
        "toColumn": "date",
        "crossFilteringBehavior": "oneDirection",
        "securityFilteringBehavior": "oneDirection"
      },
      {
        "name": "inventory_snapshot_date_to_dim_date_date",
        "fromTable": "inventory",
        "fromColumn": "snapshot_date",
        "toTable": "dim_date",
        "toColumn": "date",
        "crossFilteringBehavior": "oneDirection",
        "securityFilteringBehavior": "oneDirection"
      },
      {
        "name": "marketing_date_to_dim_date_date",
        "fromTable": "marketing",
        "fromColumn": "date",
        "toTable": "dim_date",
        "toColumn": "date",
        "crossFilteringBehavior": "oneDirection",
        "securityFilteringBehavior": "oneDirection"
      }
    ]
  }
}